FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
COPY ["JSDXTS.csproj", "./"]
RUN dotnet restore "JSDXTS.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "JSDXTS.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "JSDXTS.csproj" -c Release -o /app/publish \
    --runtime alpine-arm64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true

#https://m.imooc.com/article/316499
#https://hub.docker.com/_/microsoft-dotnet-runtime-deps

FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine-arm64v8 AS final
MAINTAINER "lpyedge"
LABEL version="0.7.1"
LABEL name="js.189.cn-speedup"
LABEL url="https://hub.docker.com/repository/docker/lpyedge/js.189.cn-speedup"
LABEL email="lpyedge#163.com"

WORKDIR /app
COPY --from=publish /app/publish .
ENV TZ=Asia/Shanghai
ENV interval=0

#包安装源切换到阿里云
#修复alpine时区设置的问题
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    apk --update add tzdata;
    
ENTRYPOINT ["/app/JSDXTS"]